import { Department, Program, Student } from '@/types/database'

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'College of Computer Studies',
    code: 'CCS',
    description: 'Department offering computer science and IT programs',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'College of Arts and Sciences',
    code: 'CAS',
    description: 'Department offering arts, humanities, and sciences programs',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'College of Business',
    code: 'CB',
    description: 'Department offering business and management programs',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockPrograms: Program[] = [
  {
    id: '1',
    name: 'Bachelor of Science in Computer Science',
    code: 'BSCS',
    description: 'A program focused on computer science fundamentals',
    department_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Bachelor of Science in Information Technology',
    code: 'BSIT',
    description: 'A program focused on information technology',
    department_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Bachelor of Arts in Psychology',
    code: 'BAP',
    description: 'A program focused on human behavior and psychology',
    department_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Bachelor of Science in Business Administration',
    code: 'BSBA',
    description: 'A program focused on business administration',
    department_id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockStudents: Student[] = [
  {
    id: '1',
    first_name: 'Juan',
    last_name: 'dela Cruz',
    age: 18,
    gender: 'Male',
    address: '123 Rizal St, Manila, Philippines',
    enrolled_year: 2024,
    program_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    first_name: 'Maria',
    last_name: 'Santos',
    age: 19,
    gender: 'Female',
    address: '456 Mabini Ave, Quezon City, Philippines',
    enrolled_year: 2024,
    program_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    first_name: 'Carlos',
    last_name: 'Reyes',
    age: 18,
    gender: 'Male',
    address: '789 Luna St, Makati, Philippines',
    enrolled_year: 2023,
    program_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    first_name: 'Ana',
    last_name: 'Garcia',
    age: 20,
    gender: 'Female',
    address: '321 Bonifacio Ave, Pasig, Philippines',
    enrolled_year: 2023,
    program_id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    first_name: 'Miguel',
    last_name: 'Torres',
    age: 19,
    gender: 'Male',
    address: '654 Aguinaldo St, Manila, Philippines',
    enrolled_year: 2024,
    program_id: '4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    first_name: 'Sofia',
    last_name: 'Mendoza',
    age: 18,
    gender: 'Female',
    address: '987 Magsaysay Blvd, Quezon City, Philippines',
    enrolled_year: 2025,
    program_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    first_name: 'Luis',
    last_name: 'Fernandez',
    age: 21,
    gender: 'Male',
    address: '147 Del Pilar St, Pasay, Philippines',
    enrolled_year: 2022,
    program_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    first_name: 'Isabella',
    last_name: 'Ramos',
    age: 19,
    gender: 'Female',
    address: '258 Roxas Blvd, Manila, Philippines',
    enrolled_year: 2023,
    program_id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    first_name: 'Diego',
    last_name: 'Cruz',
    age: 20,
    gender: 'Male',
    address: '369 Quezon Ave, Quezon City, Philippines',
    enrolled_year: 2024,
    program_id: '4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    first_name: 'Gabriela',
    last_name: 'Morales',
    age: 18,
    gender: 'Female',
    address: '741 Taft Ave, Manila, Philippines',
    enrolled_year: 2025,
    program_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    first_name: 'Rafael',
    last_name: 'Alvarez',
    age: 22,
    gender: 'Male',
    address: '852 EDSA, Makati, Philippines',
    enrolled_year: 2022,
    program_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    first_name: 'Valentina',
    last_name: 'Silva',
    age: 19,
    gender: 'Female',
    address: '963 Aurora Blvd, Quezon City, Philippines',
    enrolled_year: 2023,
    program_id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
