import { Department, Program, Student } from '@/types/database'

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'College of Computer Studies',
    code: 'CCS',
    description: 'Department offering computer science and IT programs',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'College of Arts and Sciences',
    code: 'CAS',
    description: 'Department offering arts, humanities, and sciences programs',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'College of Business',
    code: 'CB',
    description: 'Department offering business and management programs',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockPrograms: Program[] = [
  {
    id: '1',
    name: 'Bachelor of Science in Computer Science',
    code: 'BSCS',
    description: 'A program focused on computer science fundamentals',
    department_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Bachelor of Science in Information Technology',
    code: 'BSIT',
    description: 'A program focused on information technology',
    department_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Bachelor of Arts in Psychology',
    code: 'BAP',
    description: 'A program focused on human behavior and psychology',
    department_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Bachelor of Science in Business Administration',
    code: 'BSBA',
    description: 'A program focused on business administration',
    department_id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockStudents: Student[] = [
  {
    id: '1',
    first_name: 'Juan',
    last_name: 'dela Cruz',
    age: 18,
    gender: 'Male',
    address: 'Davao City',
    latitude: 7.1907,
    longitude: 125.4553,
    enrolled_year: 2024,
    program_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    first_name: 'Maria',
    last_name: 'Santos',
    age: 19,
    gender: 'Female',
    address: 'Tagum City',
    latitude: 7.4478,
    longitude: 125.8076,
    enrolled_year: 2024,
    program_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    first_name: 'Carlos',
    last_name: 'Reyes',
    age: 18,
    gender: 'Male',
    address: 'Panabo City',
    latitude: 7.3081,
    longitude: 125.6847,
    enrolled_year: 2023,
    program_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    first_name: 'Ana',
    last_name: 'Garcia',
    age: 20,
    gender: 'Female',
    address: 'Digos City',
    latitude: 6.7490,
    longitude: 125.3572,
    enrolled_year: 2023,
    program_id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    first_name: 'Miguel',
    last_name: 'Torres',
    age: 19,
    gender: 'Male',
    address: 'Davao City',
    latitude: 7.1907,
    longitude: 125.4553,
    enrolled_year: 2024,
    program_id: '4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    first_name: 'Sofia',
    last_name: 'Mendoza',
    age: 18,
    gender: 'Female',
    address: 'Mati City',
    latitude: 6.9551,
    longitude: 126.2166,
    enrolled_year: 2025,
    program_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    first_name: 'Luis',
    last_name: 'Fernandez',
    age: 21,
    gender: 'Male',
    address: 'Kidapawan City',
    latitude: 7.0083,
    longitude: 125.0896,
    enrolled_year: 2022,
    program_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    first_name: 'Isabella',
    last_name: 'Ramos',
    age: 19,
    gender: 'Female',
    address: 'General Santos City',
    latitude: 6.1164,
    longitude: 125.1716,
    enrolled_year: 2023,
    program_id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    first_name: 'Diego',
    last_name: 'Cruz',
    age: 20,
    gender: 'Male',
    address: 'Koronadal City',
    latitude: 6.5031,
    longitude: 124.8463,
    enrolled_year: 2024,
    program_id: '4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    first_name: 'Gabriela',
    last_name: 'Morales',
    age: 18,
    gender: 'Female',
    address: 'Davao City',
    latitude: 7.1907,
    longitude: 125.4553,
    enrolled_year: 2025,
    program_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    first_name: 'Rafael',
    last_name: 'Alvarez',
    age: 22,
    gender: 'Male',
    address: 'Tagum City',
    latitude: 7.4478,
    longitude: 125.8076,
    enrolled_year: 2022,
    program_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    first_name: 'Valentina',
    last_name: 'Silva',
    age: 19,
    gender: 'Female',
    address: 'Panabo City',
    latitude: 7.3081,
    longitude: 125.6847,
    enrolled_year: 2023,
    program_id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
